services:
  postgresql:
    image: postgres:16.0-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: VeryStrongPassword
      POSTGRES_USER: kodiiing
      POSTGRES_DB: kodiiing
      TZ: UTC
    healthcheck:
      test: pg_isready -U kodiiing -d kodiiing
      interval: 30s
      timeout: 20s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: local
      options:
        max-size: 10M

  typesense:
    build: ./dockerfiles/typesense
    command: --data-dir=/data --api-key=searchkey
    ports:
      - "8108:8108"
    restart: on-failure:10
    healthcheck:
      test: "curl -f http://localhost:8108/health || exit"
      interval: 30s
      timeout: 20s
      retries: 10
    volumes:
      - typesense-data:/data
    logging:
      driver: local
      options:
        max-size: 10M

  smtp:
    image: marlonb/mailcrab:latest
    ports:
      - "1025:1025"
      - "8025:1080"
    restart: on-failure:10
    logging:
      driver: local
      options:
        max-size: 2M
volumes:
  postgres-data:
  typesense-data:


